---

owner: EDRN
repo: alleviam

sites:
    -
        # We don't have a way to do ldaps: queries but we can use a service that requires LDAP
        # authorization. The MCL_BASIC_AUTH is the Base64 encoded HTTP Basic auth header
        # for the MCL service account.
        name: ℹ️ Directory Service
        url: https://mcl.jpl.nasa.gov/infirmary/v2/hello/world
        headers:
            - "Content-Type: application/json"
            - "Authorization: Basic $MCL_BASIC_AUTH"
        assignees:
            - nutjob4life
            - edrn-bot
    -
        name: 🏥 DMCC SOAP Service
        url: https://www.compass.fhcrc.org/edrn_ws/ws_newcompass.asmx?WSDL
        headers:
            - "Content-Type: text/xml; charset=utf-8"
            - "SOAPAction: \"http://www.compass.fhcrc.org/edrn_ws/ws_newcompass.asmx/Disease\""
        body: >
            <?xml version="1.0" encoding="utf-8"?>
            <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
                <soap:Body>
                    <Disease xmlns="http://www.compass.fhcrc.org/edrn_ws/ws_newcompass.asmx">
                        <verificationNum>0</verificationNum>
                    </Disease>
                </soap:Body>
            </soap:Envelope>
        assignees:
            - nutjob4life
            - edrn-bot
    -
        name: 🔑 DMCC Password Verification
        url: https://www.compass.fhcrc.org/edrn_ws/ws_newcompass.asmx?WSDL
        headers:
            - "Content-Type: text/xml; charset=utf-8"
            - "SOAPAction: \"http://www.compass.fhcrc.org/edrn_ws/ws_newcompass.asmx/pwdVerification\""
        body: >
            <?xml version="1.0" encoding="utf-8"?>
            <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
                <soap:Body>
                    <pwdVerification xmlns="http://www.compass.fhcrc.org/edrn_ws/ws_newcompass.asmx">
                        <user>$DMCC_USERNAME</user>
                        <pwd>$DMCC_PASSWORD</pwd>
                        <verificationNum>0</verificationNum>
                    </pwdVerification>
                </soap:Body>
            </soap:Envelope>
        assignees:
            - nutjob4life
    -
        name: 🚪 EDRN Portal
        url: https://edrn.nci.nih.gov/
        assignees:
            - nutjob4life
    -
        name: 🚪 EDRN Portal Login
        url: https://edrn.nci.nih.gov/@@personal-preferences
        headers:
            - "Authorization: Basic $EDRN_BASIC_AUTH"
        assignees:
            - nutjob4life
    -
        name: 🔬 EDRN LabCAS
        url: https://edrn-labcas.jpl.nasa.gov/
        assignees:
            - nutjob4life
            - yuliujpl
    -
        name: 🎪 EDRN Cancer Data Expo
        url: https://edrn.jpl.nasa.gov/cancerdataexpo/
        # JPL can't issue good certificates:
        __dangerous__disable_verify_peer: true
        assignees:
            - nutjob4life
    -
        name: 💁‍♀️ EDRN β Portal
        url: https://edrn.jpl.nasa.gov/portal/
        # JPL can't issue good certificates:
        __dangerous__disable_verify_peer: true
        assignees:
            - nutjob4life
    -
        name: 🧬 EDRN Focus Biomarker Database
        url: https://bmdb.jpl.nasa.gov/
        assignees:
            - nutjob4life
    -
        name: 🚪 MCL Portal
        url: https://mcl.nci.nih.gov/
        assignees:
            - nutjob4life
    -
        name: 🚪 MCL Portal Login
        url: https://mcl.nci.nih.gov/@@personal-preferences
        headers:
            - "Authorization: Basic $MCL_BASIC_AUTH"
        assignees:
            - nutjob4life
    -
        name: 🔬 MCL LabCAS
        url: https://mcl-labcas.jpl.nasa.gov/
        assignees:
            - nutjob4life
            - yuliujpl
    -
        name: 📚 MCL Knowledge System Database
        url: https://mcl.jpl.nasa.gov/ksdb/
        assignees:
            - nutjob4life
            - yuliujpl
    -
        name: 👩‍⚕️ MCL Infirmary Clinical Data API (v1)
        url: https://mcl.jpl.nasa.gov/infirmary/v1/ping
        assignees:
            - nutjob4life
    -
        name: 👩‍⚕️ MCL Infirmary Clinical Data API (v2)
        url: https://mcl.jpl.nasa.gov/infirmary/v2/ping
        assignees:
            - nutjob4life
    -
        name: 🧪 MCL Clinical UI
        url: https://mcl.jpl.nasa.gov/clinical-ui/
        assignees:
            - nutjob4life
            - yuliujpl
    # We cannot monitor this because it's private to JPL; however if we use a hosted runner we might
    # be able to get around this.
    # -
    #     name: 💁‍♀️ MCL β Portal
    #     url: https://mcl.jpl.nasa.gov/portal/
    #     assignees:
    #         - nutjob4life


status-website:
    # We do not have a custom domain, so leave `cname` blank:
    # cname:
    # We do not have a custom domain, so we need this `baseUrl`:
    baseUrl: /alleviam
    logoUrl: https://raw.githubusercontent.com/EDRN/alleviam/master/assets/alleviam-logo.svg
    name: Alleviam
    introTitle: "**Alleviam** is the EDRN alleviation and monitoring system."
    introMessage: >
        The status of the Early Detection Research Network (and related projects, including the Consortium for
        Molecular and Cellular Characterization of Screen-Detected Lesions) is presented below. (Icon courtesy
        of <a href='https://freepik.com/'>Freepik.com</a>.)
    # The `dark` theme looks like freakin' xmas and the `ocean` theme is too patriotic
    theme: light
    navbar:
        -
            title: Status
            href: /alleviam
        -
            title: GitHub
            href: https://github.com/$OWNER/$REPO

# Miscellaneous stuff:
skipDescriptionUpdate: true
skipTopicsUpdate: true

...
