---

# Begin

owner: EDRN
repo: alleviam

sites:
    -
        name: ðŸ§¬ðŸ”‘ Biokey
        url: https://edrn-labcas.jpl.nasa.gov/biokey/
        assignees:
            - nutjob4life
    -
        name: ðŸ¥ DMCC SOAP Service
        url: https://www.compass.fhcrc.org/edrn_ws/ws_newcompass.asmx?WSDL
        headers:
            - "Content-Type: text/xml; charset=utf-8"
            - "SOAPAction: \"http://www.compass.fhcrc.org/edrn_ws/ws_newcompass.asmx/Disease\""
        body: >
            <?xml version="1.0" encoding="utf-8"?>
            <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
                <soap:Body>
                    <Disease xmlns="http://www.compass.fhcrc.org/edrn_ws/ws_newcompass.asmx">
                        <verificationNum>0</verificationNum>
                    </Disease>
                </soap:Body>
            </soap:Envelope>
        assignees:
            - nutjob4life
            - edrn-bot
# No one uses this and it's been down since 2024-01-06, so commenting it out
# as of 2024-05-03.
#    -
#        name: ðŸ§  ML Serve
#        url: https://edrn-labcas.jpl.nasa.gov/mlserve/alphan/train
#        __dangerous__disable_verify_peer: true
#        headers:
#            - "Authorization: Basic $DMCC_BASIC_AUTH"
#        assignees:
#            - nutjob4life
#            - asitang
    -
        name: ðŸ”‘ DMCC Password Verification
        url: https://www.compass.fhcrc.org/edrn_ws/ws_newcompass.asmx?WSDL
        headers:
            - "Content-Type: text/xml; charset=utf-8"
            - "SOAPAction: \"http://www.compass.fhcrc.org/edrn_ws/ws_newcompass.asmx/pwdVerification\""
        body: >
            <?xml version="1.0" encoding="utf-8"?>
            <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
                <soap:Body>
                    <pwdVerification xmlns="http://www.compass.fhcrc.org/edrn_ws/ws_newcompass.asmx">
                        <user>$DMCC_USERNAME</user>
                        <pwd>$DMCC_PASSWORD</pwd>
                        <verificationNum>0</verificationNum>
                    </pwdVerification>
                </soap:Body>
            </soap:Envelope>
        assignees:
            - nutjob4life
    -
        name: ðŸšª EDRN Portal
        url: https://edrn.nci.nih.gov/
        assignees:
            - nutjob4life
    -
        name: âš—ï¸ NIST LabCAS authentication endpoint
        url: https://labcas.jpl.nasa.gov/nist/data-access-api/auth
        headers:
            - "Authorization: Basic $NIST_SERVICE_BASIC_AUTH"
        assignees:
            - nutjob4life
    -
        name: âš—ï¸ EDRN LabCAS authentication endpoint
        url: https://edrn-labcas.jpl.nasa.gov/data-access-api/auth
        headers:
            - "Content-type: application/x-www-form-urlencoded"
        method: POST
        body: "username=$EDRN_SERVICE_USERNAME&password=$EDRN_SERVICE_PASSWORD"
        assignees:
            - nutjob4life
    -
        name: âš—ï¸ MCL LabCAS authentication endpoint
        url: https://mcl-labcas.jpl.nasa.gov/data-access-api/auth
        headers:
            - "Content-type: application/x-www-form-urlencoded"
        method: POST
        body: "username=$MCL_SERVICE_USERNAME&password=$MCL_SERVICE_PASSWORD"
        assignees:
            - nutjob4life
    -
        name: ðŸšª EDRN Portal Login (Secure Site user)
        url: https://edrn.nci.nih.gov/authentication-test
        headers:
            - "Authorization: Basic $DMCC_BASIC_AUTH"
        assignees:
            - nutjob4life
    -
        name: ðŸ§¬ EDRN Portal Biomarker
        url: https://edrn.nci.nih.gov/data-and-resources/biomarkers/4delf
        __dangerous__body_down: "Unauthorized"
        assignees:
            - nutjob4life
    -
        name: ðŸ”¬ EDRN Portal Science Data
        url: https://edrn.nci.nih.gov/data-and-resources/data/
        assignees:
            - nutjob4life
    -
        name: ðŸ“ƒ EDRN Portal Protocol
        url: https://edrn.nci.nih.gov/data-and-resources/protocols/493-heds-reference-set-application-amit-singal-utsw-2021-prognostic-liver-secretome-signature-validation/
        __dangerous__body_down: "Unauthorized"
        assignees:
            - nutjob4life
    -
        name: ðŸ“™ EDRN Portal Publication
        url: https://edrn.nci.nih.gov/data-and-resources/publications/35199349-875-a-multivariate-parametric-empirical-bayes-screening-approach-for-early-detection-of-hepatocellular-carcinoma-using-multiple-longitudinal-biomarkers/
        __dangerous__body_down: "Unauthorized"
        assignees:
            - nutjob4life
    -
        name: ðŸ”¬ EDRN LabCAS
        url: https://edrn-labcas.jpl.nasa.gov/
        assignees:
            - nutjob4life
            - yuliujpl
    -
        name: ðŸŽª EDRN Cancer Data Expo
        url: https://edrn.jpl.nasa.gov/cancerdataexpo/
        # JPL can't issue good certificates:
        __dangerous__disable_verify_peer: true
        assignees:
            - nutjob4life
    -
        name: ðŸ§¬ EDRN Focus Biomarker Database
        url: https://bmdb.jpl.nasa.gov/
        # JPL can't issue good certificates:
        __dangerous__disable_verify_peer: true
        assignees:
            - nutjob4life
    -
        name: ðŸ”§ðŸ§¬ Dev instance of the EDRN Focus Biomarker Database
        url: https://cancer.jpl.nasa.gov/
        # JPL can't issue good certificates:
        __dangerous__disable_verify_peer: true
        assignees:
            - nutjob4life
    -
        name: ðŸ“š MCL Knowledge System Database
        url: https://mcl.jpl.nasa.gov/ksdb/
        # JPL can't issue good certificates:
        __dangerous__disable_verify_peer: true
        assignees:
            - nutjob4life
            - yuliujpl
    -
        name: ðŸ©º Test Data
        url: https://raw.githubusercontent.com/EDRN/test-data/main/etc/passwords.cfg
        assignees:
            - nutjob4life
    -
        name: ðŸ’½ðŸ”­ Data Science
        url: https://datascience.jpl.nasa.gov/
        __dangerous__disable_verify_peer: true
        assignees:
            - nutjob4life

status-website:
    # We do not have a custom domain, so leave `cname` blank:
    # cname:
    # We do not have a custom domain, so we need this `baseUrl`:
    baseUrl: /alleviam
    logoUrl: https://raw.githubusercontent.com/EDRN/alleviam/master/assets/alleviam-logo.svg
    name: Alleviam
    introTitle: "**Alleviam** is the EDRN alleviation and monitoring system."
    introMessage: >
        The status of the Early Detection Research Network (and related projects, including the Consortium for
        Molecular and Cellular Characterization of Screen-Detected Lesions) is presented below. (Icon courtesy
        of <a href='https://freepik.com/'>Freepik.com</a>.)
    # The `dark` theme looks like freakin' xmas and the `ocean` theme is too patriotic
    theme: light
    navbar:
        -
            title: Status
            href: /alleviam
        -
            title: GitHub
            href: https://github.com/$OWNER/$REPO

# Miscellaneous stuff:
skipDescriptionUpdate: true
skipTopicsUpdate: true

# End
#
...
