---

owner: EDRN
repo: alleviam

sites:
    -
        name: 🚪 EDRN Portal
        url: https://edrn.nci.nih.gov/
    -
        name: 🔬 EDRN LabCAS
        url: https://edrn-labcas.jpl.nasa.gov/
    -
        name: 🧬 Focus Biomarker Database
        url: https://bmdb.jpl.nasa.gov/
    -
        name: 🚪 MCL Portal
        url: https://mcl.nci.nih.gov/
    -
        name: 🔬 MCL LabCAS
        url: https://mcl-labcas.jpl.nasa.gov/

status-website:
    # We do not have a custom domain, so leave `cname` blank:
    # cname:
    # We do not have a custom domain, so we need this `baseUrl`:
    baseUrl: /alleviam
    logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
    name: Alleviam
    introTitle: "**Alleviam** is the EDRN alleviation and monitoring system."
    introMessage: The status of the Early Detection Research Network (and related projects, including the Consortium for Molecular and Cellular Characterization of Screen-Detected Lesions) is presented below.
    navbar:
        -
            title: Status
            href: /
        -
            title: GitHub
            href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

...
